[package]
name = "fix-rs"
version = "0.1.0"
edition = "2024"
build = "build/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roxmltree = "0.21.1"
chrono = { version = "0.4.45", features = ["serde"] }
chrono-tz = { version = "0.10", features = ["filter-by-regex", "serde"] }
indexmap = "2.14.0"
thiserror = "2.0.18"
serde = { version = "1.0", features = ["derive"] }
toml = "1.1.4"
getset = "0.1.7"
tokio = { version = "1.52.3", features = ["full"] }
derive_builder = "0.20.2"
dashmap = "6.2.1"
log = "0.4.33"
env_logger = "0.11.11"

[build-dependencies]
roxmltree = "0.21.1"
# yaserde = "0.8.0"
# yaserde_derive = "0.8.0"
xml-rs = "1.0.0"
handlebars = "6.4.3"
serde = { version = "1.0", features = ["derive"] }
heck = "0.5.0"

[dev-dependencies]
lazy_static = "1.5.0"
assert_matches = "1.5.0"
