[Default]
connection_type = "acceptor"
begin_string = "FIX.4.3"
sender_comp_id = "default_sender"
target_comp_id = "default_target"
socket_accept_port = 10113

[[Session]]
sender_comp_id = "sender1"
target_comp_id = "target1"
socket_accept_port = 10114

[[Session]]
sender_comp_id = "sender2"
target_comp_id = "target2"
socket_accept_port = 10115